// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3aW4fysc0NMn6oFmTT60704jaO7WXPjc',
    appId: '1:777611858217:web:33bab1048ecb5b6dd6a738',
    messagingSenderId: '777611858217',
    projectId: 'connekt-4187d',
    authDomain: 'connekt-4187d.firebaseapp.com',
    storageBucket: 'connekt-4187d.firebasestorage.app',
    measurementId: 'G-NGPHSD648Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJ5SsFYSLeGWoHnitrsWJ1iHnY2FyWzI',
    appId: '1:777611858217:android:45ea21291b3fe982d6a738',
    messagingSenderId: '777611858217',
    projectId: 'connekt-4187d',
    storageBucket: 'connekt-4187d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLp-oOeiOgFC1kA7zCIS0kewYKhzUn05o',
    appId: '1:777611858217:ios:be3bd9d3d6f9b292d6a738',
    messagingSenderId: '777611858217',
    projectId: 'connekt-4187d',
    storageBucket: 'connekt-4187d.firebasestorage.app',
    iosBundleId: 'com.connekt.connekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLp-oOeiOgFC1kA7zCIS0kewYKhzUn05o',
    appId: '1:777611858217:ios:be3bd9d3d6f9b292d6a738',
    messagingSenderId: '777611858217',
    projectId: 'connekt-4187d',
    storageBucket: 'connekt-4187d.firebasestorage.app',
    iosBundleId: 'com.connekt.connekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3aW4fysc0NMn6oFmTT60704jaO7WXPjc',
    appId: '1:777611858217:web:f36e7bcf870d1304d6a738',
    messagingSenderId: '777611858217',
    projectId: 'connekt-4187d',
    authDomain: 'connekt-4187d.firebaseapp.com',
    storageBucket: 'connekt-4187d.firebasestorage.app',
    measurementId: 'G-G21TYB1DKQ',
  );
}
